/**
 * Detection + parsing of static retention report HTML files.
 *
 * Report files live in /public/reports/<brandKey>/<month>-<year>.html and are
 * generated by the same offline pipeline, so their markup is predictable:
 * KPI cards (.card.kpi with .label/.val/.meta), a YoY delta on the revenue
 * card (data-yoy), and health sub-scores embedded in the inline script.
 */

import type { RetentionReport, RetentionReportStat } from '@/constants/retentionReports'

export const MONTH_NAMES = [
  'january',
  'february',
  'march',
  'april',
  'may',
  'june',
  'july',
  'august',
  'september',
  'october',
  'november',
  'december',
] as const

/**
 * Hash the retention-section password, salted with the brand id so the same
 * password produces different hashes per brand.
 */
export async function hashRetentionPassword(brandId: string, password: string): Promise<string> {
  const data = new TextEncoder().encode(`${brandId}:retention:${password}`)
  const digest = await crypto.subtle.digest('SHA-256', data)
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('')
}

export interface DetectedReportFile {
  id: string
  url: string
  fileName: string
  monthLabel: string
  year: number
  html: string
}

/** Parse an id like "june-2026" into a sortable month index, or null. */
export function parseReportId(id: string): { monthIndex: number; year: number } | null {
  const match = id.match(/^([a-z]+)-(\d{4})$/)
  if (!match) return null
  const monthIndex = MONTH_NAMES.indexOf(match[1] as (typeof MONTH_NAMES)[number])
  const year = Number(match[2])
  if (monthIndex === -1 || !year) return null
  return { monthIndex, year }
}

/** Sort key (newest = largest). Reports with unparseable ids sort oldest. */
export function reportSortKey(report: RetentionReport): number {
  const parsed = parseReportId(report.id)
  return parsed ? parsed.year * 12 + parsed.monthIndex : 0
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

/**
 * Candidate report ids to probe for, given the reports we already know about:
 * every month after the latest known report, up to one month past today.
 */
export function buildCandidateIds(existingIds: string[], now = new Date()): string[] {
  const existingKeys = existingIds
    .map(parseReportId)
    .filter((p): p is NonNullable<ReturnType<typeof parseReportId>> => p !== null)
    .map((p) => p.year * 12 + p.monthIndex)

  const currentKey = now.getFullYear() * 12 + now.getMonth()
  // No known reports: look back six months. Otherwise start after the latest.
  const startKey = existingKeys.length ? Math.max(...existingKeys) + 1 : currentKey - 6
  const endKey = currentKey + 1

  const candidates: string[] = []
  for (let key = startKey; key <= endKey && candidates.length < 12; key++) {
    candidates.push(`${MONTH_NAMES[key % 12]}-${Math.floor(key / 12)}`)
  }
  return candidates
}

/**
 * Fetch a candidate report file and verify it's a real report (and not the
 * SPA index.html served by the hosting rewrite for missing files).
 */
export async function fetchReportFile(
  brandKey: string,
  reportId: string
): Promise<DetectedReportFile | null> {
  const parsed = parseReportId(reportId)
  if (!parsed) return null

  const fileName = `${reportId}.html`
  const url = `/reports/${brandKey}/${fileName}`
  try {
    const res = await fetch(url, { cache: 'no-store' })
    if (!res.ok) return null
    const html = await res.text()
    const titleMatch = html.match(/<title>([^<]*)<\/title>/i)
    if (!titleMatch || !/klaviyo/i.test(titleMatch[1] || '')) return null
    return {
      id: reportId,
      url,
      fileName,
      monthLabel: capitalize(MONTH_NAMES[parsed.monthIndex] || ''),
      year: parsed.year,
      html,
    }
  } catch {
    return null
  }
}

interface KpiEntry {
  val: string
  meta: string
  yoy: number | null
}

function extractKpis(doc: Document): Map<string, KpiEntry> {
  const kpis = new Map<string, KpiEntry>()
  doc.querySelectorAll('.card.kpi').forEach((card) => {
    const label = card.querySelector('.label')?.textContent?.trim().toLowerCase()
    const valEl = card.querySelector('.val')
    if (!label || !valEl || kpis.has(label)) return
    const yoyRaw = card.querySelector('.kpi-delta')?.getAttribute('data-yoy')
    kpis.set(label, {
      val: valEl.textContent?.trim() || '',
      meta: card.querySelector('.meta')?.textContent?.trim() || '',
      yoy: yoyRaw != null && yoyRaw !== '' && !isNaN(Number(yoyRaw)) ? Number(yoyRaw) : null,
    })
  })
  return kpis
}

/** Compute the overall health score the same way the report's own JS does. */
function extractHealthScore(html: string): { score: number; band: string } | null {
  const subMatch = html.match(/const\s+sub\s*=\s*\{([^}]*)\}/)
  const weightMatch = html.match(/const\s+W\s*=\s*\{([^}]*)\}/)
  if (!subMatch || !weightMatch) return null

  const parsePairs = (body: string): Record<string, number> => {
    const out: Record<string, number> = {}
    for (const pair of body.split(',')) {
      const [key, value] = pair.split(':').map((s) => s.trim())
      if (key && value && !isNaN(Number(value))) out[key] = Number(value)
    }
    return out
  }

  const sub = parsePairs(subMatch[1] || '')
  const weights = parsePairs(weightMatch[1] || '')
  const keys = Object.keys(weights)
  if (!keys.length) return null

  let total = 0
  for (const key of keys) {
    if (sub[key] == null) return null
    total += sub[key] * (weights[key] || 0)
  }
  const score = Math.round(total)
  const band = score >= 75 ? 'Good' : score >= 60 ? 'Fair' : 'Needs attention'
  return { score, band }
}

/** Build the landing-page stats card by parsing a detected report file. */
export function parseReportFile(file: DetectedReportFile): RetentionReport {
  const doc = new DOMParser().parseFromString(file.html, 'text/html')
  const kpis = extractKpis(doc)

  const stats: RetentionReportStat[] = []

  const revenue = kpis.get('total attributed revenue')
  if (revenue?.val) {
    stats.push({ value: revenue.val, label: 'Attributed revenue', positive: false })
    if (revenue.yoy != null) {
      const up = revenue.yoy >= 0
      stats.push({
        value: `${up ? '▲ +' : '▼ '}${revenue.yoy.toFixed(1)}%`,
        label: 'YoY revenue',
        positive: up,
      })
    }
  }

  // The share text lives on the Flows-tab KPI ("56% of total attributed")
  const flowShare = file.html.match(/([\d.]+)%\s*of total attributed/i)
  if (flowShare?.[1]) {
    stats.push({ value: `${Math.round(Number(flowShare[1]))}%`, label: 'From flows', positive: false })
  }

  const growth = kpis.get('net list growth') || kpis.get('combined net')
  if (growth?.val) {
    stats.push({ value: growth.val, label: 'Net list growth', positive: growth.val.startsWith('+') })
  }

  const campaigns = kpis.get('campaigns sent')
  if (campaigns?.val) {
    stats.push({ value: campaigns.val, label: 'Campaigns sent', positive: false })
  }

  const chips: RetentionReport['chips'] = []
  if (doc.querySelector('#tab-perf')) chips.push({ label: 'Performance Dashboard', positive: false })
  if (doc.querySelector('#tab-creative')) chips.push({ label: 'Creative Report', positive: false })
  if (doc.querySelector('#tab-health')) chips.push({ label: 'Health Report', positive: false })
  const health = extractHealthScore(file.html)
  if (health) chips.push({ label: `Health ${health.score}/100 · ${health.band}`, positive: true })

  const lastDay = new Date(file.year, MONTH_NAMES.indexOf(file.monthLabel.toLowerCase() as (typeof MONTH_NAMES)[number]) + 1, 0).getDate()

  return {
    id: file.id,
    title: `${file.monthLabel} ${file.year} — Klaviyo Performance Report`,
    window: `Reporting window ${file.monthLabel} 1–${lastDay}, ${file.year} · Email & SMS`,
    url: file.url,
    chips,
    stats,
  }
}
